name: CI/CD Spring Boot

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/prenotazione-medica

jobs:
  ci:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build e Test
        run: mvn clean verify --settings settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: SonarQube Analysis
        run: |
          mvn sonar:sonar --settings settings.xml \
            -Dsonar.projectKey=dbalzamo_PrenotaSalute \
            -Dsonar.organization=el-dariito \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Build Docker image
        run: |
          docker build \
            --build-arg GITHUB_TOKEN=${{ secrets.GH_PACKAGES_TOKEN }} \
            --build-arg GITHUB_ACTOR=${{ github.actor }} \
            -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Login Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push immagine
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag  ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest

  #deploy:
    #name: Deploy
    #needs: ci
    #runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/master'

    #steps:
    #  - name: Deploy via SSH
    #   uses: appleboy/ssh-action@v1
    #    with:
    #      host: ${{ secrets.SERVER_HOST }}
    #      username: ${{ secrets.SERVER_USER }}
    #      key: ${{ secrets.SSH_PRIVATE_KEY }}
    #      script: |
    #        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/prenotazione-medica:latest
    #        docker-compose -f /opt/prenotazione/docker-compose.yml up -d app